require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 16

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ParameterLists:
  Max: 10

Rails/FilePath:
  Enabled: false

Metrics/BlockLength:
  Max: 40
  ExcludedMethods: ['describe']

RSpec/ExampleLength:
  Max: 25

Metrics/AbcSize:
  Max: 30

RSpec/MessageSpies:
  Enabled: false