require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/devise.rb'

Rails/BulkChangeTable:
  Enabled: false

Metrics/MethodLength:
  Max: 16
  Exclude:
    - 'db/migrate/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/FilePath:
  Enabled: false

Metrics/BlockLength:
  Max: 40
  ExcludedMethods: ['describe']
  Exclude:
    - 'app/admin/books.rb'

RSpec/ExampleLength:
  Max: 30

Metrics/AbcSize:
  Max: 30

Lint/ConstantDefinitionInBlock:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
<<<<<<< HEAD
  Max: 9
=======
  Max: 6
>>>>>>> a624084 (Add login registration pages)
