version: 2.1

executors:
  default:
    working_directory: ~/codebreaker
    description: The official CircleCI Ruby Docker image
    docker:
      # include node
      -  image: cimg/ruby:2.6.10
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_PATH: ./vendor/bundle
          RAILS_ENV: test
          DB_USERNAME: vlad
          DB_NAME: bookstore_test
          DB_PASSWORD: '6975'
      - image: circleci/postgres:14.5.0
        environment:
          POSTGRES_USER: vlad
          POSTGRES_DB: bookstore_test
          POSTGRES_PASSWORD: '6975'
          POSTGRES_HOST_AUTH_METHOD: trust

cashes:
  - &bundle_cache_full v2-codebreaker-{{ checksum "Gemfile.lock" }}
  - &bundle_cache v2-codebreaker

commands:
  defaults:
    steps:
      - checkout
      - restore_cache:
          keys:
            - *bundle_cache_full
            - *bundle_cache

      - run: bundle install --path vendor/bundle

      - save_cache:
          key: *bundle_cache_full
          paths:
            - vendor/bundle

      - restore_cache:
          keys:
            - rails-demo-yarn-{{ checksum "yarn.lock" }}
            - rails-demo-yarn-

      - run: yarn install --cache-folder ~/.cache/yarn

      - save_cache:
          key: rails-demo-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  run_rubocop:
    description: command to start rubocop
    steps:
      - run:
          name: rubocop
          command: bundle exec rubocop

  run_fasterer:
    description: command to start fasterer
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: fasterer
          command: bundle exec fasterer

  run_rspec:
    description: command to start specs
    steps:
      - run:
          name: specs
          command: |
            bin/rails db:migrate RAILS_ENV=test
            bundle exec rspec
      - store_artifacts:
          path: ~/codebreaker/coverage
          destination: coverage


jobs:
  lintering:
    executor: default
    parallelism: 2
    steps:
      - defaults
      - run_rubocop
      - run_fasterer

  rspec:
    executor: default
    steps:
      - defaults
      - run_rspec

workflows:
  build:
    jobs:
      - lintering
      - rspec:
          requires:
            - lintering