module Constants
  PAGINATION_PER_PAGE = 12

  CATALOG_BOOK_COUNT = 3
  BEST_SELLER_COUNT = 4
  DESCRIPTION_LENGTH = 25
  MIN_PRICE_IN_CENTS = 0
  MAX_PRICE_IN_CENTS = 10_000

  FOOTER_NUMBER = '(555)-555-5555'.freeze
  FOOTER_EMAIL = 'support@bookstore.com'.freeze
  REVIEW_DATE_MASK = '%m/%d/%Y'.freeze
end
